"""Seed industry_data.json from TWSE ISIN public list.

Fetches https://isin.twse.com.tw/isin/C_public.jsp?strMode=2 (上市), parses the
HTML table, maps TWSE-28 categories to Navi-11 buckets per SCREENER_ARCHITECTURE §3.1,
and overwrites backend/services/screener/industry_data.json.

Usage:
    cd backend
    uv run python scripts/seed_industry_mapping.py [--max-per-industry N] [--dry-run]
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path

import requests
from bs4 import BeautifulSoup

logger = logging.getLogger(__name__)

TWSE_ISIN_URL = "https://isin.twse.com.tw/isin/C_public.jsp?strMode=2"
OUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "services"
    / "screener"
    / "industry_data.json"
)

# TWSE-28 → Navi-11 (documented in SCREENER_ARCHITECTURE.md §3.1)
# 用「contains」配對以容納變體（如 "化學工業" / "化學生技醫療")
NAVI_BUCKETS: list[tuple[str, list[str]]] = [
    ("半導體", ["半導體"]),
    ("電子零組件", ["電子零組件", "光電", "其他電子"]),
    ("電腦及週邊", ["電腦及週邊", "電腦及周邊", "通信網路"]),
    ("電子製造", ["電子通路", "資訊服務"]),
    ("金融保險", ["金融", "證券"]),
    (
        "傳產製造",
        ["鋼鐵", "塑膠", "化學", "化工", "橡膠", "玻璃", "紡織"],
    ),
    ("航運汽車", ["航運", "汽車"]),
    ("生技醫療", ["生技", "醫療"]),
    ("民生消費", ["食品", "貿易百貨", "觀光", "居家"]),
    ("建材營造", ["建材", "水泥"]),
    ("公用其他", ["公用", "油電", "其他"]),  # fallback bucket
]


def map_to_bucket(twse_category: str) -> str:
    for bucket, keywords in NAVI_BUCKETS:
        for kw in keywords:
            if kw in twse_category:
                return bucket
    return "公用其他"


def fetch_isin_html() -> str:
    resp = requests.get(
        TWSE_ISIN_URL,
        timeout=(5, 30),
        headers={"User-Agent": "Navi/1.0 (industry mapping seed)"},
    )
    resp.raise_for_status()
    # TWSE returns big5 → use apparent encoding then re-decode
    resp.encoding = resp.apparent_encoding or "ms950"
    return resp.text


def parse_isin(html: str) -> list[tuple[str, str, str]]:
    """Return list of (ticker_with_suffix, name, twse_category).

    The TWSE ISIN page is a single big <table>. Rows have columns:
        有價證券代號及名稱 | 國際證券辨識號碼 | 上市日 | 市場別 | 產業別 | CFICode | 備註
    Only rows with 4-digit code and 市場別="上市" are kept; ETF/權證/etc. excluded.
    """
    soup = BeautifulSoup(html, "html.parser")
    rows = soup.find_all("tr")
    out: list[tuple[str, str, str]] = []
    current_section = ""

    for row in rows:
        cells = [c.get_text(strip=True) for c in row.find_all("td")]
        if len(cells) == 1:
            # 區段標題如 "股票"、"上市認購(售)權證"
            current_section = cells[0]
            continue
        if len(cells) < 5:
            continue
        if current_section and current_section != "股票":
            # 只要普通股
            continue

        code_name = cells[0]
        market = cells[3]
        category = cells[4]

        if market != "上市":
            continue

        m = re.match(r"^(\d{4})\s*[ \u3000]*(.+)$", code_name)
        if not m:
            continue
        code, name = m.group(1), m.group(2).strip()
        if not category:
            continue
        out.append((f"{code}.TW", name, category))

    return out


def build_industry_data(
    parsed: list[tuple[str, str, str]],
    max_per_industry: int | None = None,
) -> dict:
    buckets: dict[str, list[dict]] = {b: [] for b, _ in NAVI_BUCKETS}
    for ticker, name, twse_cat in parsed:
        bucket = map_to_bucket(twse_cat)
        buckets[bucket].append(
            {"ticker": ticker, "name": name, "twse_category": twse_cat}
        )
    if max_per_industry:
        for k in buckets:
            buckets[k] = buckets[k][:max_per_industry]
    return {
        "_comment": (
            "Auto-generated by scripts/seed_industry_mapping.py from TWSE ISIN list. "
            "Maps TWSE-28 categories to Navi-11 buckets per SCREENER_ARCHITECTURE §3.1."
        ),
        "industries": buckets,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed industry_data.json from TWSE")
    parser.add_argument(
        "--max-per-industry",
        type=int,
        default=None,
        help="Cap each Navi bucket size (useful for testing).",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print summary only.")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    logger.info("Fetching %s …", TWSE_ISIN_URL)
    html = fetch_isin_html()
    parsed = parse_isin(html)
    logger.info("Parsed %d listed stocks", len(parsed))

    data = build_industry_data(parsed, max_per_industry=args.max_per_industry)

    print("\nNavi-11 bucket sizes:")
    for bucket, items in data["industries"].items():
        print(f"  {bucket:<10} {len(items):>4} stocks")
    print(f"  total: {sum(len(v) for v in data['industries'].values())}")

    if args.dry_run:
        print("\n--dry-run: not writing file")
        return

    OUT_PATH.write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"\n✓ Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
